package main

const (
	authenticationToken              = "AuthToken"
	domain                           = "localhost"
	cookieMaxAge                     = 0
	adminRole                        = "admin"
	distributorRole                  = "distributor"
	invalidCredentials               = "Invalid Credentials"
	successfulLogin                  = "Successfully Logged in"
	alreadyLogin                     = "Already Logged in"
	methodNotAllowed                 = "Method Not allowed"
	loginFirst                       = "Please Log in first"
	notAuthorizedToCreateAdmin       = "Not Authorized to create admin Users"
	userCreated                      = "Successfully created user"
	nameAlreadyExists                = "name already exists"
	invalidParent                    = "Invalid Parent"
	emptyPassword                    = "Empty Password"
	nameCannotBeEmpty                = "Name cannot be empty"
	roleCannotBeEmpty                = "Role cannot be empty"
	internalServerError              = "Internal Server error"
	cannotExcludeWithoutInclude      = "Cannot Exclude Locations Without Including Locations"
	invalidIncludeLocation           = "Invalid Include location"
	invalidExcludeLocation           = "Invalid Exclude location"
	countryNameCannotBeEmpty         = "Country Name cannot be empty"
	cannotGiveCityWithoutProvince    = "Cannot give City without Province"
	countryProvinceCityCannotBeEmpty = "Country, Province, City cannot be empty"
	locationNotFound                 = "No location Found for given Country, Province, City"
	distributionPermitted            = "distributionPermitted"
	notAuthorized                    = "Not Authorized"
	adminUsersCannotDistribute       = "Admin Users cannot Distribute"
	notAuthorizedToDistribute        = "User Not Authorized To Distribute"
)
