// Package app provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package app

// DistributorDetails defines model for DistributorDetails.
type DistributorDetails struct {
	// Exclude List of items to exclude
	Exclude []Location `json:"exclude"`
	Include []Location `json:"include"`

	// Name Name of the distributor
	Name string `json:"name"`

	// ParentDistributor parent distributor
	ParentDistributor string `json:"parentDistributor"`
}

// Location defines model for Location.
type Location struct {
	City     string `json:"city"`
	Country  string `json:"country"`
	Province string `json:"province"`
}

// CheckPermissionJSONBody defines parameters for CheckPermission.
type CheckPermissionJSONBody struct {
	Location Location `json:"location"`
	Name     string   `json:"name"`
}

// AddDistributorJSONRequestBody defines body for AddDistributor for application/json ContentType.
type AddDistributorJSONRequestBody = DistributorDetails

// CheckPermissionJSONRequestBody defines body for CheckPermission for application/json ContentType.
type CheckPermissionJSONRequestBody CheckPermissionJSONBody
