// Package app provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package app

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Add a new distributor
	// (POST /addDistributor)
	AddDistributor(c *gin.Context)

	// (POST /check-permissions)
	CheckPermission(c *gin.Context)

	// (GET /getDistributor/{distributor-name})
	GetDistributorDetailsByName(c *gin.Context, distributorName string)

	// (GET /getall/{cntry-name})
	GetCntryDetailsByCntryName(c *gin.Context, cntryName string)
	// Get permissions for a distributor
	// (GET /permission/{distributorName})
	GetPermissionsByName(c *gin.Context, distributorName string)
	// Add a new distributor
	// (GET /status)
	GetStatus(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AddDistributor operation middleware
func (siw *ServerInterfaceWrapper) AddDistributor(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.AddDistributor(c)
}

// CheckPermission operation middleware
func (siw *ServerInterfaceWrapper) CheckPermission(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.CheckPermission(c)
}

// GetDistributorDetailsByName operation middleware
func (siw *ServerInterfaceWrapper) GetDistributorDetailsByName(c *gin.Context) {

	var err error

	// ------------- Path parameter "distributor-name" -------------
	var distributorName string

	err = runtime.BindStyledParameter("simple", false, "distributor-name", c.Param("distributor-name"), &distributorName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter distributor-name: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDistributorDetailsByName(c, distributorName)
}

// GetCntryDetailsByCntryName operation middleware
func (siw *ServerInterfaceWrapper) GetCntryDetailsByCntryName(c *gin.Context) {

	var err error

	// ------------- Path parameter "cntry-name" -------------
	var cntryName string

	err = runtime.BindStyledParameter("simple", false, "cntry-name", c.Param("cntry-name"), &cntryName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cntry-name: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetCntryDetailsByCntryName(c, cntryName)
}

// GetPermissionsByName operation middleware
func (siw *ServerInterfaceWrapper) GetPermissionsByName(c *gin.Context) {

	var err error

	// ------------- Path parameter "distributorName" -------------
	var distributorName string

	err = runtime.BindStyledParameter("simple", false, "distributorName", c.Param("distributorName"), &distributorName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter distributorName: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetPermissionsByName(c, distributorName)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetStatus(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/addDistributor", wrapper.AddDistributor)

	router.POST(options.BaseURL+"/check-permissions", wrapper.CheckPermission)

	router.GET(options.BaseURL+"/getDistributor/:distributor-name", wrapper.GetDistributorDetailsByName)

	router.GET(options.BaseURL+"/getall/:cntry-name", wrapper.GetCntryDetailsByCntryName)

	router.GET(options.BaseURL+"/permission/:distributorName", wrapper.GetPermissionsByName)

	router.GET(options.BaseURL+"/status", wrapper.GetStatus)

	return router
}
