// Code generated by "stringer -type=LocationType"; DO NOT EDIT

package domain

import "fmt"

const _LocationType_name = "CountryStateCity"

var _LocationType_index = [...]uint8{0, 7, 12, 16}

func (i LocationType) String() string {
	i -= 1
	if i < 0 || i >= LocationType(len(_LocationType_index)-1) {
		return fmt.Sprintf("LocationType(%d)", i+1)
	}
	return _LocationType_name[_LocationType_index[i]:_LocationType_index[i+1]]
}
