// Code generated by "stringer -type=Permission"; DO NOT EDIT

package domain

import "fmt"

const _Permission_name = "GrantedDeniedNotDefined"

var _Permission_index = [...]uint8{0, 7, 13, 23}

func (i Permission) String() string {
	i -= 1
	if i < 0 || i >= Permission(len(_Permission_index)-1) {
		return fmt.Sprintf("Permission(%d)", i+1)
	}
	return _Permission_name[_Permission_index[i]:_Permission_index[i+1]]
}
